name: Build and Push Image to ghcr

on:
  push:
    branches:
      - main
    paths:
      - 'application-java/**'

  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate docker image tag
        id: generate-image-tag
        run: echo "IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV && echo $IMAGE_TAG

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_NAME }}
          flavor: latest=true
          tags: |
            type=sha,prefix=,suffix=,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: application-java
          push: true
          tags: ghcr.io/${{ env.IMG_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64

# new job to create PR in main branch to update the manifest with latest image tag
  create-pr:
    runs-on: ubuntu-latest
    needs: build-and-push # This job depends on the 'build' job
    if: needs.build-and-push.result == 'success'
    env:
      IMG_NAME: ${{ github.repository }}    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for creating new branches and pushing

      - name: Generate docker image tag
        id: generate-image-tag
        run: echo "IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV && echo $IMAGE_TAG

      - name: Update image tag in a file (example)
        run: |
          sed -i "s|ghcr.io/ravichaudhary11/fluxxd2-test:.*|ghcr.io/ravichaudhary11/fluxxd2-test:${{ env.IMAGE_TAG }}|g" manifests/nginx/deployment-java.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/nginx/deployment-java.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Update image to ${{ steps.generate_tag.outputs.NEW_TAG }}"
          title: "Automated: Update image to ${{ steps.generate_tag.outputs.NEW_TAG }}"
          body: |
            This pull request updates the image tag to `${{ steps.generate_tag.outputs.NEW_TAG }}`.
            Generated by GitHub Actions.
          branch: "automated/image-update-${{ github.run_number }}" # New branch for the PR
          base: main # Target branch for the PR
          labels: automated-pr, enhancement
          draft: false

