name: push-artifact

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'manifests/**'
jobs:
  package-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ORAS CLI
        uses: oras-project/setup-oras@v1

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push YAML
        run: |
          oras push ghcr.io/${{ github.repository_owner }}/java:latest \
            --artifact-type application/vnd.cncf.helm.config.v1+json \
            ./manifests:application/vnd.cncf.helm.chart.content.v1.tar+gzip